### ISSUE TITLE
cookies alias

### ISSUE THREAD

**Issue by vlinder** [JAAulde/jquery-cookies#1]
Is it just me or is cookies not being aliased into the jQuery namespace an mentioned?

> The entire cookies singleton API from [JAAulde/cookies](https://github.com/JAAulde/cookies/) is aliased in the jQuery namespace. For example, `cookies.set()` is available as `$.cookies.set()`.

**Comment by JAAulde** [comment]
Oh my--you are correct! How did that happen!? I am fixing this immediately!

**Comment by JAAulde** [comment]
release v3.0.3 has been pushed with this fix
